# Generated by Django 4.2.19 on 2025-02-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_category_alter_product_image_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
